url = ""
title = "Novels"

[novels.oap_en]
title = "桃子和橙子 英文版"
audio = "books/oap_en/audio/"
cn = "books/oap_en/cn/cn.txt"

[novels.oap_en.chap]
1 = {en = "books/oap_en/0001.txt", title = "第1章 反派？但我是病娇"}
2 = {en = "books/oap_en/0002.txt", title = "第2章 待定"}

