url = ""
title = "Novels"

[novels.oap_en]
title = "桃子和橙子 英文版"
audio = "books/oap_en/audio/"
cn = "books/oap_en/cn/cn.txt"

[novels.nomoney_en]
title = "借贷修仙 英文版"
audio = "books/nomoney_en/audio/"
cn = "books/nomoney_en/cn/cn_new.txt"

[novels.oap_en.chap]
1 = {en = "books/oap_en/0001.txt", title = "第1章 反派？但我是病娇"}
2 = {en = "books/oap_en/0002.txt", title = "第2章 喜欢你喜欢你喜欢你"}
3 = {en = "books/oap_en/0003.txt", title = "第3章 要坏掉惹"}
4 = {en = "books/oap_en/0004.txt", title = "第4章 她的味道"}
5 = {en = "books/oap_en/0005.txt", title = "第5章 对不起你，但喜欢你"}
6 = {en = "books/oap_en/0006.txt", title = "第6章 让她抱憾终身"}
7 = {en = "books/oap_en/0007.txt", title = "第7章 约见男主"}
8 = {en = "books/oap_en/0008.txt", title = "第8章 看傻了的男主"}
9 = {en = "books/oap_en/0009.txt", title = "第9章 收割情绪值！"}
10 = {en = "books/oap_en/0010.txt", title = "第10章 威胁"}
11 = {en = "books/oap_en/0011.txt", title = "第11章 重要剧情点，校内球赛"}
12 = {en = "books/oap_en/0012.txt", title = "第12章 你不喜欢喝水吗"}
13 = {en = "books/oap_en/0013.txt", title = "第13章 你再说一遍！"}
14 = {en = "books/oap_en/0014.txt", title = "第14章 新的计划（谢谢汐汐是也的打赏）"}
15 = {en = "books/oap_en/0015.txt", title = "第15章 你什么时候回来呀？"}
16 = {en = "books/oap_en/0016.txt", title = "第16章 她的偏执"}
17 = {en = "books/oap_en/0017.txt", title = "第17章 难道我还没池小橙重要吗！（谢谢人无完人的狄修打赏）"}
18 = {en = "books/oap_en/0018.txt", title = "第18章 对我来说，她比你更重要"}
19 = {en = "books/oap_en/0019.txt", title = "第19章 这是礼物吗？"}
20 = {en = "books/oap_en/0020.txt", title = "第20章 我变成这样，都是因为你呢~"}
21 = {en = "books/oap_en/0021.txt", title = "第21章 老天爷在敲门"}
22 = {en = "books/oap_en/0022.txt", title = "第22章 放心，我又不是真的病娇"}
23 = {en = "books/oap_en/0023.txt", title = "第23章 让女主爱上我"}
24 = {en = "books/oap_en/0024.txt", title = "第24章 你知道病娇吗？"}
25 = {en = "books/oap_en/0025.txt", title = "第25章 你喜欢过她吗？"}
26 = {en = "books/oap_en/0026.txt", title = "第26章 你喜欢吗？"}
27 = {en = "books/oap_en/0027.txt", title = "第27章 她怪可爱的"}
28 = {en = "books/oap_en/0028.txt", title = "第28章 谎言"}
29 = {en = "books/oap_en/0029.txt", title = "第29章 你怎么不朝我撒娇？"}
30 = {en = "books/oap_en/0030.txt", title = "第30章 系统奖励，巨大提升！"}
31 = {en = "books/oap_en/0031.txt", title = "第31章 危机，被怀疑了！"}
32 = {en = "books/oap_en/0032.txt", title = "第32章 昔日的“姐妹”"}
33 = {en = "books/oap_en/0033.txt", title = "第33章 踩雷"}
34 = {en = "books/oap_en/0034.txt", title = "第34章 黑化前兆"}
35 = {en = "books/oap_en/0035.txt", title = "第35章 不像演的"}
36 = {en = "books/oap_en/0036.txt", title = "第36章 割裂的人设"}
37 = {en = "books/oap_en/0037.txt", title = "第37章 打消怀疑"}
38 = {en = "books/oap_en/0038.txt", title = "第38章 苏桃：小橙她真的是病娇吗？"}
39 = {en = "books/oap_en/0039.txt", title = "第39章 你养的病娇，你不知道？"}
40 = {en = "books/oap_en/0040.txt", title = "第40章 你只能是我的！"}
41 = {en = "books/oap_en/0041.txt", title = "第41章 反派哥哥竟是橙桃党？"}
42 = {en = "books/oap_en/0042.txt", title = "第42章 她喜欢你的原因"}
43 = {en = "books/oap_en/0043.txt", title = "第43章 洗白弱三分，黑化强十倍"}
44 = {en = "books/oap_en/0044.txt", title = "第44章 橙医生：老夫最懂病娇了"}
45 = {en = "books/oap_en/0045.txt", title = "第45章 黑化"}
46 = {en = "books/oap_en/0046.txt", title = "第46章 宿主你正常点，本系统害怕"}
47 = {en = "books/oap_en/0047.txt", title = "第47章 来都来了（加更）"}
48 = {en = "books/oap_en/0048.txt", title = "第48章 短暂的温存"}
49 = {en = "books/oap_en/0049.txt", title = "第49章 我扮演的是病娇，不是疯子"}
50 = {en = "books/oap_en/0050.txt", title = "第50章 她的时间，只能有她（加更）"}
51 = {en = "books/oap_en/0051.txt", title = "第51章 爱她，就把一切都给她"}
52 = {en = "books/oap_en/0052.txt", title = "第52章 她是真正的病娇！"}
53 = {en = "books/oap_en/0053.txt", title = "第53章 要好好接受治疗才行呢~"}
54 = {en = "books/oap_en/0054.txt", title = "第54章 不断重复的绝望"}
55 = {en = "books/oap_en/0055.txt", title = "第55章 病娇的爱，独一无二（为kira加更）"}
56 = {en = "books/oap_en/0056.txt", title = "第56章 一根手指"}
57 = {en = "books/oap_en/0057.txt", title = "第57章 池小橙的三步计划"}
58 = {en = "books/oap_en/0058.txt", title = "第58章 苏桃沦陷的开始（为代欧奇希斯加更）"}
59 = {en = "books/oap_en/0059.txt", title = "第59章 你已经有点喜欢我了哦~"}
60 = {en = "books/oap_en/0060.txt", title = "第60章 有病有娇，才是病娇"}
61 = {en = "books/oap_en/0061.txt", title = "第61章 危机，叶良到来！（为布灵布灵的黑猫加更）"}
62 = {en = "books/oap_en/0062.txt", title = "第62章 统子，你黑化技能怎么没用啊"}
63 = {en = "books/oap_en/0063.txt", title = "第63章 她病娇的对象，是苏桃！"}
64 = {en = "books/oap_en/0064.txt", title = "第64章 撕破脸皮，不死不休（为夜入星繁加更）"}
65 = {en = "books/oap_en/0065.txt", title = "第65章 给小橙找个心理医生"}
66 = {en = "books/oap_en/0066.txt", title = "第66章 哥哥回归"}
67 = {en = "books/oap_en/0067.txt", title = "第67章 我和叶良掉水里，你救谁（为x旋律-加更）"}
68 = {en = "books/oap_en/0068.txt", title = "第68章 桃桃，我一直在看着你哦"}
69 = {en = "books/oap_en/0069.txt", title = "第69章 去约会吧~"}
70 = {en = "books/oap_en/0070.txt", title = "第70章 生米煮成熟饭（为茅台不好喝加更）"}
71 = {en = "books/oap_en/0071.txt", title = "第71章 喜欢的不是包子，而是你"}
72 = {en = "books/oap_en/0072.txt", title = "第72章 第一次心动"}
73 = {en = "books/oap_en/0073.txt", title = "第73章 设局（为鹿野凛加更）"}
74 = {en = "books/oap_en/0074.txt", title = "第74章 接受她，或者抛弃她"}
75 = {en = "books/oap_en/0075.txt", title = "第76章 崩坏、迷茫、痛苦（为迅音玲兔加更）"}
76 = {en = "books/oap_en/0076.txt", title = "第76章 崩坏、迷茫、痛苦（为迅音玲兔加更）"}
77 = {en = "books/oap_en/0077.txt", title = "第77章 依赖的起始"}
78 = {en = "books/oap_en/0078.txt", title = "第78章 苏桃的“未来”"}
79 = {en = "books/oap_en/0079.txt", title = "第79章 你逃不掉的哦（谢谢無度索求的礼物之王）"}
80 = {en = "books/oap_en/0080.txt", title = "第80章 一环扣一环"}
81 = {en = "books/oap_en/0081.txt", title = "第81章 桃子小姐，你也是个病娇"}
82 = {en = "books/oap_en/0082.txt", title = "第82章 病娇的闭环（为...不知道取啥名加更）"}
83 = {en = "books/oap_en/0083.txt", title = "第83章 致敬抗压王牢桃"}
84 = {en = "books/oap_en/0084.txt", title = "第84章 我对你的喜欢，是装的"}
85 = {en = "books/oap_en/0085.txt", title = "第85章 品尝她的病娇（为空天垄清加更）"}
86 = {en = "books/oap_en/0086.txt", title = "第86章 桃桃真单纯呢"}
87 = {en = "books/oap_en/0087.txt", title = "第87章 你想要的，我会给你"}

[novels.nomoney_en.chap]
1 = {en = "books/nomoney_en/0001.txt", title = "第1章 面试"}
2 = {en = "books/nomoney_en/0002.txt", title = "第2章 学校"}
3 = {en = "books/nomoney_en/0003.txt", title = "第3章 体育"}
4 = {en = "books/nomoney_en/0004.txt", title = "第4章 请神"}
5 = {en = "books/nomoney_en/0005.txt", title = "第5章 羽书"}
6 = {en = "books/nomoney_en/0006.txt", title = "第6章 自由"}
7 = {en = "books/nomoney_en/0007.txt", title = "第7章 人和人的差距"}
8 = {en = "books/nomoney_en/0008.txt", title = "第8章 老师的关心"}
9 = {en = "books/nomoney_en/0009.txt", title = "第9章 工作"}
10 = {en = "books/nomoney_en/0010.txt", title = "第10章 竞争激烈和3级健体"}
11 = {en = "books/nomoney_en/0011.txt", title = "第11章 周天采气"}
12 = {en = "books/nomoney_en/0012.txt", title = "第12章 勇猛精进（感谢‘水"}
13 = {en = "books/nomoney_en/0013.txt", title = "第13章 法赛"}
14 = {en = "books/nomoney_en/0014.txt", title = "第14章 准备和新工作"}
15 = {en = "books/nomoney_en/0015.txt", title = "第15章 中心大厦"}
16 = {en = "books/nomoney_en/0016.txt", title = "第16章 巡逻"}
17 = {en = "books/nomoney_en/0017.txt", title = "第17章 分数和秘辛"}
18 = {en = "books/nomoney_en/0018.txt", title = "第18章 天人演武图"}
19 = {en = "books/nomoney_en/0019.txt", title = "第19章 惊怖和道心"}
20 = {en = "books/nomoney_en/0020.txt", title = "第20章 参悟"}
21 = {en = "books/nomoney_en/0021.txt", title = "第21章 天武炼心"}
22 = {en = "books/nomoney_en/0022.txt", title = "第22章 合同"}
23 = {en = "books/nomoney_en/0023.txt", title = "第23章 谈"}
24 = {en = "books/nomoney_en/0024.txt", title = "第24章 灵根"}
25 = {en = "books/nomoney_en/0025.txt", title = "第25章 气海"}
26 = {en = "books/nomoney_en/0026.txt", title = "第26章 报名法赛和月考到来"}
27 = {en = "books/nomoney_en/0027.txt", title = "第27章 考间冲刺"}
28 = {en = "books/nomoney_en/0028.txt", title = "第28章 道术和实战"}